### ISSUE TITLE
ReadMe does not provide link to paper in ACM/IEEE digital library

### ISSUE THREAD

**Issue by satish2** [SoftwareEngineeringToolDemos/FSE-2010-Ref-Finder#1]

**Comment by egmulky** [comment]
Readme already has the paper link "Reference: Research Paper: Template-based Reconstruction of Complex Refactorings, Kyle Prete, Napol Rachatasumrit, Nikita Sudan, and Miryung Kim, ICSM '10"

**Comment by egmulky** [comment]
Tool Demo: Ref-Finder: a Refactoring Reconstruction Tool based on Logic Query Templates, Miryung Kim, Matthew Gee, Alex Loh, and Napol Rachatasumrit, FSE' 10

**Comment by egmulky** [comment]
Please check the readme properly before creating an issue. Donot create an issue for things that are already there.
