### ISSUE TITLE
Few inconsistencies in ReadMe file

### ISSUE THREAD

**Issue by satish2** [SoftwareEngineeringToolDemos/FSE-2010-Ref-Finder#4]
1. While thanking author, link to author's website is not attached to author's name which I found generally followed by other students.
2. In readme, in one or two locations, Author's have used "we" while mentioning the work they were carrying on. Given that, we are just testing the tool, I think it is not appropriate to use "we".

**Comment by egmulky** [comment]
This has been forked from the Author's git. I am not allowed to change the author's readme. 
The author has no website.
